### ISSUE TITLE
Reporte de Practica 3

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-3-practica-architect-Arlet04#1]
[Practica 3 Jeanette Arlet Salazar Nicolás.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Arlet04/files/12554090/Practica.3.Jeanette.Arlet.Salazar.Nicolas.pdf)

**Comment by Eve-lizet** [comment]
Calificacion 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
